In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
veriler = pd.read_csv("veriler.csv")

In [18]:
eksikveri=pd.read_csv("eksikveri.csv")

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [21]:
yas = eksikveri.iloc[:,1:4].values
yas

array([[130.,  30.,  10.],
       [125.,  36.,  11.],
       [135.,  34.,  10.],
       [133.,  30.,   9.],
       [129.,  38.,  12.],
       [180.,  90.,  30.],
       [190.,  80.,  25.],
       [175.,  90.,  35.],
       [177.,  60.,  22.],
       [185., 105.,  33.],
       [165.,  55.,  27.],
       [155.,  50.,  44.],
       [160.,  58.,  nan],
       [162.,  59.,  41.],
       [167.,  62.,  55.],
       [174.,  70.,  47.],
       [193.,  90.,  nan],
       [187.,  80.,  27.],
       [183.,  88.,  28.],
       [159.,  40.,  29.],
       [164.,  66.,  32.],
       [166.,  56.,  42.]])

In [22]:
imputer = imputer.fit(yas[:,1:4])
yas[:,1:4] = imputer.transform(yas[:,1:4])

In [23]:
yas

array([[130.  ,  30.  ,  10.  ],
       [125.  ,  36.  ,  11.  ],
       [135.  ,  34.  ,  10.  ],
       [133.  ,  30.  ,   9.  ],
       [129.  ,  38.  ,  12.  ],
       [180.  ,  90.  ,  30.  ],
       [190.  ,  80.  ,  25.  ],
       [175.  ,  90.  ,  35.  ],
       [177.  ,  60.  ,  22.  ],
       [185.  , 105.  ,  33.  ],
       [165.  ,  55.  ,  27.  ],
       [155.  ,  50.  ,  44.  ],
       [160.  ,  58.  ,  28.45],
       [162.  ,  59.  ,  41.  ],
       [167.  ,  62.  ,  55.  ],
       [174.  ,  70.  ,  47.  ],
       [193.  ,  90.  ,  28.45],
       [187.  ,  80.  ,  27.  ],
       [183.  ,  88.  ,  28.  ],
       [159.  ,  40.  ,  29.  ],
       [164.  ,  66.  ,  32.  ],
       [166.  ,  56.  ,  42.  ]])

In [24]:
ulke = veriler.iloc[:,0:1].values

In [25]:
from sklearn import preprocessing

In [26]:
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

In [27]:
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [28]:
c = veriler.iloc[:,-1:].values

In [29]:
le = preprocessing.LabelEncoder()
c[:,-1] = le.fit_transform(veriler.iloc[:,-1])

In [30]:
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
c

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [31]:
sonuc = pd.DataFrame(data=ulke,columns=["fr","tr","us"])
sonuc2 = pd.DataFrame(data=yas,index=range(22),columns=["boy","kilo","yas"])

In [32]:
cinsiyet = veriler.iloc[:,-1].values
sonuc3 = pd.DataFrame(data=c[:,:1],index=range(22),columns=["cinsiyet"])
s = pd.concat([sonuc,sonuc2],axis=1)

In [38]:
s2 = pd.concat([s,sonuc3],axis=1)
s2

fr   tr   us    boy   kilo    yas  cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.00       1.0
1   0.0  1.0  0.0  125.0   36.0  11.00       1.0
2   0.0  1.0  0.0  135.0   34.0  10.00       0.0
3   0.0  1.0  0.0  133.0   30.0   9.00       0.0
4   0.0  1.0  0.0  129.0   38.0  12.00       1.0
5   0.0  1.0  0.0  180.0   90.0  30.00       1.0
6   0.0  1.0  0.0  190.0   80.0  25.00       1.0
7   0.0  1.0  0.0  175.0   90.0  35.00       1.0
8   0.0  1.0  0.0  177.0   60.0  22.00       0.0
9   0.0  0.0  1.0  185.0  105.0  33.00       1.0
10  0.0  0.0  1.0  165.0   55.0  27.00       0.0
11  0.0  0.0  1.0  155.0   50.0  44.00       0.0
12  0.0  0.0  1.0  160.0   58.0  28.45       0.0
13  0.0  0.0  1.0  162.0   59.0  41.00       0.0
14  0.0  0.0  1.0  167.0   62.0  55.00       0.0
15  1.0  0.0  0.0  174.0   70.0  47.00       1.0
16  1.0  0.0  0.0  193.0   90.0  28.45       1.0
17  1.0  0.0  0.0  187.0   80.0  27.00       1.0
18  1.0  0.0  0.0  183.0   88.0  28.00       1.0
19  1.0  0.0  0.0  159.0   40.0  29.00       0.0
20  1.0  0.0  0.0  164.0   66.0  32.00       0.0
21  1.0  0.0  0.0  166.0   56.0  42.00       0.0

In [34]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
regression = LinearRegression()

In [96]:
regression.fit(x_train,y_train)

LinearRegression()

In [97]:
y_predict = regression.predict(x_test)

In [93]:
s2
boy = s2.iloc[:,3:4].values
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]
veri = pd.concat([sol,sag],axis=1)
veri

fr   tr   us   kilo    yas  cinsiyet
0   0.0  1.0  0.0   30.0  10.00       1.0
1   0.0  1.0  0.0   36.0  11.00       1.0
2   0.0  1.0  0.0   34.0  10.00       0.0
3   0.0  1.0  0.0   30.0   9.00       0.0
4   0.0  1.0  0.0   38.0  12.00       1.0
5   0.0  1.0  0.0   90.0  30.00       1.0
6   0.0  1.0  0.0   80.0  25.00       1.0
7   0.0  1.0  0.0   90.0  35.00       1.0
8   0.0  1.0  0.0   60.0  22.00       0.0
9   0.0  0.0  1.0  105.0  33.00       1.0
10  0.0  0.0  1.0   55.0  27.00       0.0
11  0.0  0.0  1.0   50.0  44.00       0.0
12  0.0  0.0  1.0   58.0  28.45       0.0
13  0.0  0.0  1.0   59.0  41.00       0.0
14  0.0  0.0  1.0   62.0  55.00       0.0
15  1.0  0.0  0.0   70.0  47.00       1.0
16  1.0  0.0  0.0   90.0  28.45       1.0
17  1.0  0.0  0.0   80.0  27.00       1.0
18  1.0  0.0  0.0   88.0  28.00       1.0
19  1.0  0.0  0.0   40.0  29.00       0.0
20  1.0  0.0  0.0   66.0  32.00       0.0
21  1.0  0.0  0.0   56.0  42.00       0.0

In [94]:
x_train,x_test,y_train,y_test=train_test_split(veri,boy,test_size=0.33,random_state=0)

In [98]:
r2 = LinearRegression()
r2.fit(x_train,y_train)

LinearRegression()

In [99]:
y_pred = r2.predict(x_test)

In [100]:
y_test

array([[164.],
       [165.],
       [167.],
       [162.],
       [125.],
       [166.],
       [155.],
       [159.]])

In [101]:
y_pred

array([[182.25496542],
       [153.60175918],
       [163.03243328],
       [158.79170543],
       [130.88751593],
       [173.75783348],
       [150.54725552],
       [157.27677179]])

In [36]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()

In [37]:
# X_train = sc.fit_transform(x_train)
# X_test = sc.fit_transform(x_test)

In [102]:
import statsmodels.api as sm

In [104]:
X = np.append(arr = np.ones((22,1)).astype(int), values=veri,axis=1)

In [105]:
X

array([[  1.  ,   0.  ,   1.  ,   0.  ,  30.  ,  10.  ,   1.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  36.  ,  11.  ,   1.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  34.  ,  10.  ,   0.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  30.  ,   9.  ,   0.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  38.  ,  12.  ,   1.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  90.  ,  30.  ,   1.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  80.  ,  25.  ,   1.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  90.  ,  35.  ,   1.  ],
       [  1.  ,   0.  ,   1.  ,   0.  ,  60.  ,  22.  ,   0.  ],
       [  1.  ,   0.  ,   0.  ,   1.  , 105.  ,  33.  ,   1.  ],
       [  1.  ,   0.  ,   0.  ,   1.  ,  55.  ,  27.  ,   0.  ],
       [  1.  ,   0.  ,   0.  ,   1.  ,  50.  ,  44.  ,   0.  ],
       [  1.  ,   0.  ,   0.  ,   1.  ,  58.  ,  28.45,   0.  ],
       [  1.  ,   0.  ,   0.  ,   1.  ,  59.  ,  41.  ,   0.  ],
       [  1.  ,   0.  ,   0.  ,   1.  ,  62.  ,  55.  ,   0.  ],
       [  1.  ,   1.  ,  

In [106]:
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.886
Model:                            OLS   Adj. R-squared:                  0.850
Method:                 Least Squares   F-statistic:                     24.85
Date:                Fri, 10 Sep 2021   Prob (F-statistic):           5.17e-07
Time:                        11:49:13   Log-Likelihood:                -73.887
No. Observations:                  22   AIC:                             159.8
Df Residuals:                      16   BIC:                             166.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           113.6364      8.087     14.052      0.000      96.493     130.780
x2           108.1800      5.644     19.167      0.000      96.215     120.145
x3           104.1324      8.840     11.780      0.000      85.393     122.871
x4             0.9142      0.120      7.624      0.000       0.660       1.168
x5             0.1054      0.221      0.478      0.639      -0.362       0.573
x6           -10.5082      5.005     -2.099      0.052     -21.119       0.102
==============================================================================
Omnibus:                        1.129   Durbin-Watson:                   2.772
Prob(Omnibus):                  0.569   Jarque-Bera (JB):                0.679
Skew:                           0.426   Prob(JB):                        0.712
Kurtosis:                       2.878   Cond. No.                         513.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [124]:
"""
Burada x değişkenlerindeki p-values değerlerinin en yüksek olanını elemek.
Çoklu doğrusal regression modelinde sapmaları minimize etmek.

Yukarıda ki tabloda x5 değişkeninin p-value değeri yüksek : 0.639
bunu aşağıda ki tabloda eledik

index değerine göre 4 kolonu çıkartıp aşağıda modeli tekrar test ettik

Multiple Linear Regression / Çoklu doğrusal regression
y = B0 + B1x1 + B2x2 + B3x3 + E.
"""


X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Fri, 10 Sep 2021   Prob (F-statistic):           9.32e-08
Time:                        12:17:14   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [118]:
veri.iloc[:,4]
veri.drop("yas",axis=1)

fr   tr   us   kilo  cinsiyet
0   0.0  1.0  0.0   30.0       1.0
1   0.0  1.0  0.0   36.0       1.0
2   0.0  1.0  0.0   34.0       0.0
3   0.0  1.0  0.0   30.0       0.0
4   0.0  1.0  0.0   38.0       1.0
5   0.0  1.0  0.0   90.0       1.0
6   0.0  1.0  0.0   80.0       1.0
7   0.0  1.0  0.0   90.0       1.0
8   0.0  1.0  0.0   60.0       0.0
9   0.0  0.0  1.0  105.0       1.0
10  0.0  0.0  1.0   55.0       0.0
11  0.0  0.0  1.0   50.0       0.0
12  0.0  0.0  1.0   58.0       0.0
13  0.0  0.0  1.0   59.0       0.0
14  0.0  0.0  1.0   62.0       0.0
15  1.0  0.0  0.0   70.0       1.0
16  1.0  0.0  0.0   90.0       1.0
17  1.0  0.0  0.0   80.0       1.0
18  1.0  0.0  0.0   88.0       1.0
19  1.0  0.0  0.0   40.0       0.0
20  1.0  0.0  0.0   66.0       0.0
21  1.0  0.0  0.0   56.0       0.0

In [119]:
x_train,x_test,y_train,y_test=train_test_split(veri.drop("yas",axis=1),boy,test_size=0.33,random_state=0)

In [120]:
r3 = LinearRegression()
r3.fit(x_train,y_train)

LinearRegression()

In [121]:
y_pred = r3.predict(x_test)

In [122]:
y_test

array([[164.],
       [165.],
       [167.],
       [162.],
       [125.],
       [166.],
       [155.],
       [159.]])

In [123]:
y_pred

array([[181.89803222],
       [153.24827689],
       [160.08774579],
       [157.15654483],
       [131.11471282],
       [172.12736238],
       [148.36294197],
       [156.49429062]])