In [1]:
import numpy as np

In [3]:
benimDizim=np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [9]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [10]:
benimDizim[3:8] = -5

In [11]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [12]:
baskaDizi = np.arange(0,24)

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
slicingDizi=baskaDizi[4:9]

In [15]:
slicingDizi

array([4, 5, 6, 7, 8])

In [18]:
slicingDizi[:] = 700

In [19]:
slicingDizi

array([700, 700, 700, 700, 700])

In [20]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [21]:
ornekDizi=np.arange(0,24)

In [22]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekDiziKopyasi=ornekDizi.copy()

In [24]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
ornekDiziKopyasiSlicing=ornekDiziKopyasi[3:6]

In [27]:
ornekDiziKopyasiSlicing[:]=800

In [28]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [29]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [30]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix 

In [31]:
benimListem=[[10,20,30],[20,30,40],[30,40,50]]

In [32]:
benimMatrixDizim=np.array(benimListem)

In [33]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [34]:
benimMatrixDizim[0]

array([10, 20, 30])

In [35]:
benimMatrixDizim[1][2]

40

In [36]:
benimMatrixDizim[1,2]

40

In [37]:
benimMatrixDizim[1:,2]

array([40, 50])

In [38]:
 benimMatrixDizim[0:,1:]

array([[20, 30],
       [30, 40],
       [40, 50]])

In [39]:
yeniListe= [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [40]:
yeniMatrix=np.array(yeniListe)

In [41]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## farklı operasyonlar

In [48]:
yeniBirDizi=np.random.randint(1,100,20)

In [49]:
yeniBirDizi

array([84, 11, 90, 67, 10, 71, 37, 68, 97, 61, 58, 71, 60, 18,  4, 96,  1,
       93, 30, 76])

In [50]:
yeniBirDizi > 24

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True])

In [51]:
yeniBirDizi

array([84, 11, 90, 67, 10, 71, 37, 68, 97, 61, 58, 71, 60, 18,  4, 96,  1,
       93, 30, 76])

In [52]:
sonucDizisi = yeniBirDizi > 24

In [53]:
sonucDizisi

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True])

In [56]:
# true olanları alıyor
yeniBirDizi[sonucDizisi]

array([84, 90, 67, 71, 37, 68, 97, 61, 58, 71, 60, 96, 93, 30, 76])

In [57]:
yeniBirDizi[yeniBirDizi>24]

array([84, 90, 67, 71, 37, 68, 97, 61, 58, 71, 60, 96, 93, 30, 76])

In [58]:
sonDizi=np.arange(0,24)

In [60]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [61]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [62]:
sonDizi ** sonDizi

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989,
                 0,   878082373,   977272832, -1276351769], dtype=int32)

In [64]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [63]:
sonDizi / sonDizi

C:\Users\YAKUP\AppData\Local\Temp/ipykernel_8532/1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [66]:
np.max(sonDizi)

23

In [67]:
np.min(sonDizi)

0

In [68]:
np.max(np.sqrt(sonDizi))

4.795831523312719