In [1]:
import numpy as np

## numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [6]:
np.array(matrixListesi) #aşağıdaki görünüm "matrix"

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [14]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [15]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [16]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## eye

In [17]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [18]:
np.random.randn(8)

array([-1.13628673, -1.08247147, -1.48207598,  2.71319724, -0.57138005,
       -1.005001  , -0.0899068 , -0.07774388])

In [19]:
np.random.randn(4,4)

array([[-0.00510237, -0.84997661,  0.04557563,  0.61088732],
       [ 1.07631831, -1.22200393,  0.45641487, -0.76708498],
       [-0.32981712, -0.20811116, -0.56729475,  0.73414447],
       [-0.26463294,  0.77860266,  0.36147889,  0.01632072]])

In [20]:
np.random.randint(1,10)

7

In [21]:
np.random.randint(1,300,5)

array([208, 172,  32, 147, 252])

In [22]:
benimNumpyDizim=np.arange(30)

In [23]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
benimRandomDizim=np.random.randint(0,100,30)

In [25]:
benimRandomDizim

array([73, 78, 66, 10, 73, 79,  7, 30, 46, 56,  8, 35, 48, 60, 31, 26, 16,
       38, 99, 88, 84, 51, 85, 65, 42, 15,  2, 52, 16, 72])

## numpy dizi methodları

In [26]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
benimNumpyDizim.max()

29

In [28]:
benimRandomDizim.max()

99

In [29]:
benimRandomDizim.min()

2

In [30]:
benimRandomDizim.argmax()

18

In [31]:
benimRandomDizim.argmin()

26

In [32]:
benimNumpyDizim.shape

(30,)

In [33]:
reshapeDizim=benimNumpyDizim.reshape(5,6)

In [34]:
reshapeDizim.shape

(5, 6)